version: '3.8'

services:
  # image gallery web app
  app:
    image: godcandidate/image-gallery:latest
    restart: always
    ports:
      - "80:3001"
    environment:
      # Database
      DB_HOST: $DB_HOST
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PORT: 3001
      # AWS S3
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
