name: Deploy to Docker Hub

on:
  push:
    branches: [rds_feature]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build, tag, and push image to Docker Hub
        env:
          DOCKER_HUB_REPOSITORY: ${{ secrets.DOCKER_USERNAME }}/image-gallery-app
          IMAGE_TAG: latest
        run: |
          docker build -t $DOCKER_HUB_REPOSITORY:$IMAGE_TAG .
          docker push $DOCKER_HUB_REPOSITORY:$IMAGE_TAG
          echo "Image pushed to Docker Hub with tag: $IMAGE_TAG"
